FROM golang:1.25-alpine AS build

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build \
    -o /out/noblifi-radius \
    ./cmd/radius

FROM alpine:3.22

RUN apk add --no-cache ca-certificates tzdata

WORKDIR /app

COPY --from=build \
    /out/noblifi-radius \
    /app/noblifi-radius

EXPOSE 1812/udp
EXPOSE 1813/udp

CMD ["/app/noblifi-radius"]
